<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AceMq.Amqp/AceMq.Amqp.csproj" />
    <ProjectReference Include="../../src/AceMq.Amqp.RabbitMq/AceMq.Amqp.RabbitMq.csproj" />
    <ProjectReference Include="../../src/AceMq.Amqp.Diagnostics/AceMq.Amqp.Diagnostics.csproj" />
    <ProjectReference Include="../../src/AceMq.Amqp.Protobuf/AceMq.Amqp.Protobuf.csproj" />
    <ProjectReference Include="../../src/AceMq.Amqp.Avro/AceMq.Amqp.Avro.csproj" />
    <ProjectReference Include="../../src/AceMq.Amqp.DevCerts/AceMq.Amqp.DevCerts.csproj" />
    <ProjectReference Include="../../src/AceMq.Amqp.Yaml/AceMq.Amqp.Yaml.csproj" />
  </ItemGroup>

</Project>
