// Copyright 2026 AceMQ.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Globalization;
using System.Text.Json;
using AceMq.Amqp;

namespace AceMq.Amqp.Tests;

/// <summary>
/// Asserts this library against <c>fixtures/contract-fixtures.json</c>, the retry
/// schedule, queue names and topology every AceMQ library has to agree on.
/// </summary>
/// <remarks>
/// <para>
/// The fixture is generated by the Java library's own test suite and copied here byte
/// for byte; <c>../scripts/check-fixtures.sh</c> fails if any library's copy has
/// drifted by a character. Nothing in this file may edit it. When this library
/// disagrees with it, the disagreement is written down as a disagreement — a named,
/// asserted exception saying what .NET does and what the fixture says — rather than
/// smoothed away by relaxing an assertion, because four other repositories carry the
/// same bytes and a fixture that has been quietly bent to fit one of them is worse
/// than no fixture at all.
/// </para>
/// <para>
/// This is why the file exists. Java shipped <c>exponential</c> with a multiplier of
/// five and ten percent jitter for ten releases while Go, .NET, Python and Ruby all
/// doubled with twenty — <c>exponential(5, 1s, 1m)</c> gave <c>1s, 5s, 25s, 60s</c>
/// there and <c>1s, 2s, 4s, 8s</c> here — and nobody noticed for months, because every
/// library tested its own arithmetic against its own expectations and passed.
/// </para>
/// <para>
/// So the assertions here derive their expectations wherever they can rather than
/// reading a number out of the fixture and comparing it to the same number read out of
/// this library, which proves only that both can be read. The doubling is checked by
/// asserting each delay is twice its predecessor; the threshold table is recomputed
/// from the rule the fixture states in prose; the rung names are rendered a second
/// time by an obvious implementation written in this file; the jitter bounds are
/// sampled from this library and checked against the bounds, never read back.
/// </para>
/// </remarks>
public sealed class ContractConformanceTests
{
    // ---- the fixture -----------------------------------------------------

    private static JsonElement Fixture()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "contract-fixtures.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.Clone();
    }

    private static JsonElement Section(string name) => Fixture().GetProperty(name);

    private const string Queue = "orders.new";

    private static TimeSpan Millis(long value) => TimeSpan.FromMilliseconds(value);

    private static long[] MillisOf(IEnumerable<TimeSpan> delays) =>
        delays.Select(d => (long)d.TotalMilliseconds).ToArray();

    private static long[] LongsOf(JsonElement array) =>
        array.EnumerateArray().Select(e => e.GetInt64()).ToArray();

    /// <summary>
    /// The .NET policy for a fixture schedule, built from what the fixture's
    /// <c>how</c> field says rather than from the numbers it records.
    /// </summary>
    /// <remarks>
    /// The whole point of the exercise: the fixture names a policy in prose, both
    /// libraries construct it, and the delays that come out are compared. Reading
    /// <c>scheduleMillis</c> and feeding it back in would assert nothing.
    /// </remarks>
    private static RetryPolicy PolicyNamed(string name) => name switch
    {
        "exponential-uncapped" =>
            RetryPolicy.Exponential(5, TimeSpan.FromSeconds(1), TimeSpan.FromHours(24)),
        "exponential-capped" =>
            RetryPolicy.Exponential(6, TimeSpan.FromSeconds(10), TimeSpan.FromMinutes(1)),
        "exponential-give-up-on-age" =>
            RetryPolicy.Exponential(5, TimeSpan.FromSeconds(1), TimeSpan.FromHours(24))
                .GiveUpAfter(TimeSpan.FromMinutes(2)),
        "fixed" => RetryPolicy.Fixed(4, TimeSpan.FromSeconds(30)),
        "none" => RetryPolicy.None(),
        _ => throw new InvalidOperationException($"no policy named '{name}'"),
    };

    private static JsonElement ScheduleNamed(string name)
    {
        foreach (var entry in Section("retrySchedules").EnumerateArray())
        {
            if (entry.GetProperty("name").GetString() == name) return entry;
        }
        throw new InvalidOperationException($"no fixture schedule named '{name}'");
    }

    /// <summary>
    /// Java's default age ceiling, which this library does not have.
    /// </summary>
    /// <remarks>
    /// Java's <c>RetryPolicy</c> constructs every policy with
    /// <c>Duration.ofDays(365)</c> as its maximum message age, so the fixture records
    /// a real limit of 31,536,000,000ms on every policy that was never asked to give
    /// up on age at all. This library — and, per its own comment, the Python and Ruby
    /// ones — use zero as "never", so a message that is exactly a year old is still
    /// retried here and dead-lettered there. See
    /// <see cref="EveryRetryDecisionMatchesExceptTheAgeCeilingOnlyJavaApplies"/>.
    /// </remarks>
    private const long JavaDefaultMaxMessageAgeMillis = 31_536_000_000L;

    // ---- retrySchedules --------------------------------------------------

    [Theory]
    [InlineData("exponential-uncapped")]
    [InlineData("exponential-capped")]
    [InlineData("exponential-give-up-on-age")]
    [InlineData("fixed")]
    [InlineData("none")]
    public void EveryNamedPolicyProducesTheScheduleTheFixtureRecords(string name)
    {
        var fixture = ScheduleNamed(name);
        var policy = PolicyNamed(name);

        Assert.Equal(fixture.GetProperty("maxAttempts").GetInt32(), policy.MaxAttempts);
        Assert.Equal(fixture.GetProperty("jitterFactor").GetDouble(), policy.JitterFactor);
        Assert.Equal(
            fixture.GetProperty("brokerWaitThresholdMillis").GetInt64(),
            (long)policy.BrokerWaitThreshold.TotalMilliseconds);

        // The delays themselves. A library that agrees about the parameters and
        // disagrees about the arithmetic is the failure this fixture was built for.
        Assert.Equal(
            LongsOf(fixture.GetProperty("scheduleMillis")),
            MillisOf(policy.Schedule()));
    }

    [Theory]
    [InlineData("exponential-uncapped")]
    [InlineData("exponential-capped")]
    [InlineData("exponential-give-up-on-age")]
    [InlineData("fixed")]
    [InlineData("none")]
    public void EveryNamedPolicyNeedsTheRungQueuesTheFixtureRecords(string name)
    {
        // The rungs are the queues two services declare independently, so a policy
        // that needs a different set of them in one language is a PRECONDITION_FAILED
        // waiting for the second service to start.
        Assert.Equal(
            LongsOf(ScheduleNamed(name).GetProperty("brokerRungDelaysMillis")),
            MillisOf(PolicyNamed(name).BrokerRungs()));
    }

    [Fact]
    public void TheExponentialSchedulesActuallyDoubleUntilTheyReachTheirCeiling()
    {
        // Derived rather than read. Comparing the fixture's numbers to this library's
        // numbers proves they match; asserting that each is twice the one before it
        // proves the multiplier is two, which is the thing Java got wrong for ten
        // releases while every library's own tests passed.
        foreach (var (name, ceilingMillis) in new[]
                 {
                     ("exponential-uncapped", 24L * 60 * 60 * 1000),
                     ("exponential-capped", 60L * 1000),
                 })
        {
            var schedule = MillisOf(PolicyNamed(name).Schedule());
            Assert.Equal(LongsOf(ScheduleNamed(name).GetProperty("scheduleMillis")), schedule);

            for (var i = 1; i < schedule.Length; i++)
            {
                var doubled = schedule[i - 1] * 2;
                Assert.True(
                    schedule[i] == doubled || (schedule[i] == ceilingMillis && doubled > ceilingMillis),
                    $"{name}[{i}] is {schedule[i]}ms; twice its predecessor is {doubled}ms and the "
                    + $"ceiling is {ceilingMillis}ms");
            }
        }
    }

    [Theory]
    [InlineData("exponential-uncapped")]
    [InlineData("exponential-capped")]
    [InlineData("exponential-give-up-on-age")]
    [InlineData("fixed")]
    [InlineData("none")]
    public void EveryRetryDecisionMatchesExceptTheAgeCeilingOnlyJavaApplies(string name)
    {
        var fixture = ScheduleNamed(name);
        var policy = PolicyNamed(name);
        var fixtureLimit = fixture.GetProperty("maxMessageAgeMillis").GetInt64();

        // Every row where this library and the fixture answer differently, collected
        // rather than asserted one at a time, so that the set of disagreements can be
        // pinned exactly. A new disagreement fails here; so does one of these
        // disappearing, which is what happens when somebody resolves it.
        var disagreements = new List<string>();
        var rows = 0;

        foreach (var decision in fixture.GetProperty("decisions").EnumerateArray())
        {
            rows++;
            var attempt = decision.GetProperty("attempt").GetInt32();
            var age = decision.GetProperty("messageAgeMillis").GetInt64();
            var fixtureRetries = decision.GetProperty("retries").GetBoolean();
            var here = policy.NextWait(attempt, Millis(age)) != null;

            if (here != fixtureRetries)
            {
                disagreements.Add(
                    $"attempt={attempt} age={age}ms fixture={fixtureRetries} dotnet={here}");
            }
        }

        Assert.True(rows > 0, "the fixture recorded no decisions for " + name);

        // The only disagreement, and only for the policies that were never given an
        // age limit at all: Java gives every policy a default ceiling of 365 days, so
        // it stops retrying a message that has reached exactly that age. This library
        // treats "no limit" as no limit, and keeps going. The two rows are the ones
        // the fixture generator produced by walking to the limit it believed in.
        var expected = new List<string>();
        if (fixtureLimit == JavaDefaultMaxMessageAgeMillis && policy.MaxAttempts > 1)
        {
            expected.Add(
                $"attempt=1 age={JavaDefaultMaxMessageAgeMillis}ms fixture=False dotnet=True");
            expected.Add(
                $"attempt={policy.MaxAttempts - 1} age={JavaDefaultMaxMessageAgeMillis}ms "
                + "fixture=False dotnet=True");
        }

        Assert.Equal(expected, disagreements);
    }

    [Fact]
    public void ThisLibraryHasNoDefaultAgeCeilingWhereJavaHasOneOfAYear()
    {
        // The disagreement above, stated once as the property it is rather than as a
        // list of rows. Zero means never here, in Python and in Ruby; Java has no way
        // to say never and uses 365 days for it, which then leaves the Java library as
        // the only one of the five that will refuse to retry a very old message.
        Assert.Equal(TimeSpan.Zero, RetryPolicy.Exponential(5, TimeSpan.FromSeconds(1)).MaxMessageAge);
        Assert.Equal(TimeSpan.Zero, RetryPolicy.Fixed(4, TimeSpan.FromSeconds(30)).MaxMessageAge);
        Assert.Equal(TimeSpan.Zero, RetryPolicy.None().MaxMessageAge);

        foreach (var schedule in Section("retrySchedules").EnumerateArray())
        {
            var recorded = schedule.GetProperty("maxMessageAgeMillis").GetInt64();
            var asked = schedule.GetProperty("name").GetString() == "exponential-give-up-on-age";
            Assert.Equal(asked ? 120_000L : JavaDefaultMaxMessageAgeMillis, recorded);
        }

        // Where an age limit was actually asked for, the two agree exactly.
        var giveUp = PolicyNamed("exponential-give-up-on-age");
        Assert.Equal(TimeSpan.FromMinutes(2), giveUp.MaxMessageAge);
        Assert.NotNull(giveUp.NextWait(1, Millis(119_999)));
        Assert.Null(giveUp.NextWait(1, Millis(120_000)));
    }

    // ---- jitter ----------------------------------------------------------

    [Fact]
    public void JitterMovesAConsumerWaitBothWaysAndStaysInsideTheMultipliers()
    {
        var fixture = Section("jitter");
        var factor = fixture.GetProperty("factor").GetDouble();

        // The fixture's own two multipliers have to be the factor either side of one,
        // or the section disagrees with itself before any library is consulted.
        Assert.True(fixture.GetProperty("appliesInBothDirections").GetBoolean());
        Assert.Equal(1 - factor, fixture.GetProperty("minMultiplier").GetDouble(), 9);
        Assert.Equal(1 + factor, fixture.GetProperty("maxMultiplier").GetDouble(), 9);
        Assert.True(fixture.GetProperty("appliesToConsumerWaits").GetBoolean());
        Assert.False(fixture.GetProperty("appliesToBrokerWaits").GetBoolean());

        var policy = PolicyNamed(fixture.GetProperty("policy").GetString()!);
        Assert.Equal(factor, policy.JitterFactor);

        // Sampled from this library rather than read back out of the file. The bounds
        // are the claim; twenty thousand draws are what turns the claim into evidence.
        var baseDelay = policy.Schedule()[0];
        var low = long.MaxValue;
        var high = long.MinValue;
        for (var i = 0; i < 20_000; i++)
        {
            var wait = policy.NextWait(1, TimeSpan.Zero);
            Assert.NotNull(wait);
            Assert.False(wait!.InBroker, "a one-second wait belongs in the consumer");
            var sampled = (long)wait.Delay.TotalMilliseconds;
            low = Math.Min(low, sampled);
            high = Math.Max(high, sampled);
        }

        var baseMillis = (long)baseDelay.TotalMilliseconds;
        Assert.True(low < baseMillis, $"jitter never shortened the delay: low was {low}ms");
        Assert.True(high > baseMillis, $"jitter never lengthened the delay: high was {high}ms");
        Assert.True(
            low >= baseMillis * (1 - factor),
            $"jitter went below its own bound: {low}ms against {baseMillis * (1 - factor)}ms");
        Assert.True(
            high <= baseMillis * (1 + factor),
            $"jitter went above its own bound: {high}ms against {baseMillis * (1 + factor)}ms");

        // And never below the floor, which is the other half of the fixture's claim.
        var floor = fixture.GetProperty("flooredAtMillis").GetInt64();
        Assert.True(low >= floor, $"a consumer wait of {low}ms fell below the floor of {floor}ms");
    }

    [Fact]
    public void AWaitHeldInTheBrokerIsNeverJittered()
    {
        var factor = Section("jitter").GetProperty("factor").GetDouble();

        // A rung queue's time-to-live is fixed when it is declared, so a moved delay
        // names a queue nobody created. This is the assertion that a library which
        // jitters uniformly would fail.
        var policy = RetryPolicy.Fixed(2, TimeSpan.FromMinutes(1)).WithJitter(factor);
        for (var i = 0; i < 1_000; i++)
        {
            var wait = policy.NextWait(1, TimeSpan.Zero);
            Assert.NotNull(wait);
            Assert.True(wait!.InBroker);
            Assert.Equal(60_000d, wait.Delay.TotalMilliseconds);
        }
    }

    [Fact]
    public void TheJitterFloorIsWholeMillisecondsInJavaAndSubMillisecondHere()
    {
        // The fixture's flooredAtMillis of 1 is not a constant Java declares; it is
        // the smallest wait its generator saw from fixed(2, 1ms).withJitter(1.0), and
        // it is 1 because Java's applyJitter ends in Math.max(1, ...). This library
        // multiplies a TimeSpan and floors at zero, so the same policy produces waits
        // of a fraction of a millisecond.
        //
        // It costs nothing — the difference is between sleeping 0.3ms and sleeping
        // 1ms, on a policy nobody writes — but it is a difference, and the fixture
        // states its floor as a rule rather than as an observation, so it is asserted
        // here as what this library actually does rather than left to be discovered.
        var floor = Section("jitter").GetProperty("flooredAtMillis").GetInt64();
        Assert.Equal(1L, floor);

        var tiny = RetryPolicy.Fixed(2, TimeSpan.FromMilliseconds(1)).WithJitter(1.0);
        var lowest = double.MaxValue;
        for (var i = 0; i < 5_000; i++)
        {
            var wait = tiny.NextWait(1, TimeSpan.Zero);
            Assert.NotNull(wait);
            Assert.False(wait!.InBroker);
            Assert.True(wait.Delay >= TimeSpan.Zero, "a delay is never negative");
            lowest = Math.Min(lowest, wait.Delay.TotalMilliseconds);
        }

        Assert.True(
            lowest < floor,
            $"this library floored a jittered millisecond at {lowest}ms; Java floors it at {floor}ms, "
            + "and if that has changed here the fixture and this comment both need revisiting");

        // The floor the fixture states does hold for every delay the fixture's own
        // jitter section is about, which is why this is a latent difference rather
        // than a live one: a rung is only reached at or above the broker-wait
        // threshold, and a consumer wait of a millisecond is not something a policy in
        // this repository produces.
        var real = PolicyNamed("exponential-uncapped");
        for (var i = 0; i < 1_000; i++)
        {
            Assert.True(real.NextWait(1, TimeSpan.Zero)!.Delay.TotalMilliseconds >= floor);
        }
    }

    // ---- brokerWaitThreshold ---------------------------------------------

    [Fact]
    public void TheBrokerWaitThresholdTableIsWhatThisLibraryDecides()
    {
        var fixture = Section("brokerWaitThreshold");
        Assert.Equal(
            fixture.GetProperty("defaultMillis").GetInt64(),
            (long)RetryPolicy.DefaultBrokerWaitThreshold.TotalMilliseconds);
        Assert.Equal(
            Fixture().GetProperty("defaultBrokerWaitThresholdMillis").GetInt64(),
            (long)RetryPolicy.DefaultBrokerWaitThreshold.TotalMilliseconds);

        var rows = 0;
        foreach (var row in fixture.GetProperty("cases").EnumerateArray())
        {
            rows++;
            var threshold = row.GetProperty("thresholdMillis").GetInt64();
            var delay = row.GetProperty("delayMillis").GetInt64();
            var expected = row.GetProperty("waitsInBroker").GetBoolean();

            var policy = RetryPolicy.Fixed(2, TimeSpan.FromSeconds(1))
                .WaitInBrokerFrom(Millis(threshold));

            Assert.Equal(expected, policy.WaitsInBroker(Millis(delay)));
        }

        // Thirty rows, not "some rows". A fixture that lost half its table would
        // otherwise pass this test in silence.
        Assert.Equal(30, rows);
    }

    [Fact]
    public void TheThresholdTableIsTheStatedRuleRecomputed()
    {
        // The fixture states the rule in prose and then tabulates it. Recomputing the
        // table from the prose catches a generator that tabulated something else —
        // the one thing comparing two implementations to each other cannot catch,
        // because they would both be compared to the same wrong table.
        var fixture = Section("brokerWaitThreshold");
        var rule = fixture.GetProperty("rule").GetString()!;
        Assert.Contains("at or above the threshold", rule);
        Assert.Contains("threshold of zero sends nothing to the broker", rule);

        foreach (var row in fixture.GetProperty("cases").EnumerateArray())
        {
            var threshold = row.GetProperty("thresholdMillis").GetInt64();
            var delay = row.GetProperty("delayMillis").GetInt64();

            var byTheRule = threshold > 0 && delay > 0 && delay >= threshold;

            Assert.Equal(byTheRule, row.GetProperty("waitsInBroker").GetBoolean());
        }
    }

    [Fact]
    public void AThresholdOfZeroDeclaresNoRungAtAll()
    {
        // The rule's second sentence, followed through to the topology it implies.
        var ladder = RetryLadder.For(
            Queue,
            RetryPolicy.Exponential(6, TimeSpan.FromSeconds(10), TimeSpan.FromMinutes(5))
                .WaitInBrokerFrom(TimeSpan.Zero));

        Assert.True(ladder.IsEmpty);
        Assert.Empty(ladder.Queues);
    }

    // ---- naming ----------------------------------------------------------

    /// <summary>
    /// The rung-name rule written a second time, the obvious way.
    /// </summary>
    /// <remarks>
    /// Deliberately not a call into <see cref="Naming"/>. Two readings of the same
    /// method agree with each other by construction; two implementations of the same
    /// rule only agree if the rule is what both of them implement.
    /// </remarks>
    private static string RenderDelayTheObviousWay(long millis)
    {
        if (millis <= 0) return "0s";
        if (millis % 3_600_000 == 0) return Digits(millis / 3_600_000) + "h";
        if (millis % 60_000 == 0) return Digits(millis / 60_000) + "m";
        if (millis % 1_000 == 0) return Digits(millis / 1_000) + "s";
        return Digits(millis) + "ms";
    }

    private static string Digits(long value) => value.ToString(CultureInfo.InvariantCulture);

    [Fact]
    public void TheDeadLetterAndParkedQueuesAreNamedTheWayEveryLibraryNamesThem()
    {
        var fixture = Section("naming");
        var queue = fixture.GetProperty("queue").GetString()!;
        Assert.Equal(Queue, queue);

        Assert.Equal(fixture.GetProperty("deadLetterQueue").GetString(), Naming.DeadLetterQueue(queue));
        Assert.Equal(fixture.GetProperty("parkedQueue").GetString(), Naming.ParkedQueue(queue));

        // And the same two names derived from the suffixes rather than from the
        // method, so that a change to both at once still fails.
        Assert.Equal(queue + ".dlq", Naming.DeadLetterQueue(queue));
        Assert.Equal(queue + ".parked", Naming.ParkedQueue(queue));
        Assert.Equal(".dlq", Naming.DeadLetterSuffix);
        Assert.Equal(".parked", Naming.ParkedSuffix);

        Assert.Equal(Naming.DeadLetterExchange, Fixture().GetProperty("deadLetterExchange").GetString());
        Assert.Equal(RetryLadder.RetryExchange, Fixture().GetProperty("retryExchange").GetString());
    }

    [Fact]
    public void EveryRungQueueIsNamedForItsDelay()
    {
        var rows = 0;
        foreach (var row in Section("naming").GetProperty("retryQueues").EnumerateArray())
        {
            rows++;
            var millis = row.GetProperty("delayMillis").GetInt64();
            var expected = row.GetProperty("queue").GetString();

            Assert.Equal(expected, Naming.RetryQueue(Queue, Millis(millis)));

            // The second implementation. If both this and Naming.Describe were wrong
            // in the same way the fixture would still catch it; this catches the case
            // where the fixture is wrong in the same way as Naming.Describe.
            Assert.Equal(expected, Queue + ".retry." + RenderDelayTheObviousWay(millis));
        }

        Assert.Equal(6, rows);
    }

    [Fact]
    public void ThisLibraryRendersASubSecondRungTheWayJavaDoesAndNotTheWayGoPythonAndRubyDo()
    {
        // The one disagreement the fixture records rather than settles. Java renders
        // 500ms as orders.new.retry.500ms; Go, Python and Ruby divide by a thousand
        // and render orders.new.retry.0s. This library is on Java's side, which its
        // own Naming.Describe already says in a comment and which is asserted here so
        // that it is a fact rather than a claim.
        //
        // Not resolved here, and not resolvable here: the fixture is shared, and the
        // three libraries on the other side would have to move at the same time.
        var disagreement = Section("naming").GetProperty("subSecondDisagreement").GetString()!;
        Assert.Contains("orders.new.retry.500ms", disagreement);
        Assert.Contains("orders.new.retry.0s", disagreement);

        var name = Naming.RetryQueue(Queue, TimeSpan.FromMilliseconds(500));
        Assert.Equal("orders.new.retry.500ms", name);
        Assert.NotEqual("orders.new.retry.0s", name);
        Assert.Equal("500ms", Naming.Describe(TimeSpan.FromMilliseconds(500)));

        // Unreachable through the default threshold, which is what keeps it a
        // difference on paper. A rung only exists at or above thirty seconds.
        Assert.True(
            RetryLadder.For(Queue, RetryPolicy.Fixed(3, TimeSpan.FromMilliseconds(500))).IsEmpty);
    }

    // ---- rungArguments ---------------------------------------------------

    [Fact]
    public void EveryRungCarriesExactlyThreeArgumentsAndTheSameThree()
    {
        var rows = 0;
        foreach (var row in Section("rungArguments").EnumerateArray())
        {
            rows++;
            var millis = row.GetProperty("delayMillis").GetInt64();
            var expected = row.GetProperty("arguments");

            Assert.Equal(row.GetProperty("queue").GetString(), Naming.RetryQueue(Queue, Millis(millis)));

            var actual = RetryLadder.ArgumentsFor(Queue, Millis(millis));

            // The count as well as the values. A fourth argument — a length limit, an
            // overflow policy, anything somebody adds locally — is a
            // PRECONDITION_FAILED for the second service that declares this queue,
            // and it would slip past an assertion that only checked the three it
            // knew about.
            Assert.Equal(3, actual.Count);
            Assert.Equal(
                expected.EnumerateObject().Select(p => p.Name).OrderBy(n => n, StringComparer.Ordinal),
                actual.Keys.OrderBy(n => n, StringComparer.Ordinal));

            Assert.Equal(millis, Convert.ToInt64(actual[RetryLadder.MessageTtlArgument]));
            Assert.Equal(
                expected.GetProperty("x-message-ttl").GetInt64(),
                Convert.ToInt64(actual[RetryLadder.MessageTtlArgument]));
            Assert.Equal(
                expected.GetProperty("x-dead-letter-exchange").GetString(),
                actual[RetryLadder.DeadLetterExchangeArgument]);
            Assert.Equal(
                expected.GetProperty("x-dead-letter-routing-key").GetString(),
                actual[RetryLadder.DeadLetterRoutingKeyArgument]);

            // The routing key is the source queue, not the rung. A rung that sent its
            // expiries back to itself would loop forever.
            Assert.Equal(Queue, actual[RetryLadder.DeadLetterRoutingKeyArgument]);
        }

        Assert.Equal(6, rows);
    }

    // ---- topology --------------------------------------------------------

    private static RetryPolicy TopologyPolicy() =>
        RetryPolicy.Exponential(6, TimeSpan.FromSeconds(10), TimeSpan.FromMinutes(5));

    [Fact]
    public void TheTopologyPolicyIsTheOneTheFixtureDescribes()
    {
        var fixture = Section("topology");
        Assert.Equal(Queue, fixture.GetProperty("sourceQueue").GetString());
        Assert.Equal(
            LongsOf(fixture.GetProperty("policyScheduleMillis")),
            MillisOf(TopologyPolicy().Schedule()));
        Assert.Equal(
            LongsOf(fixture.GetProperty("policyRungDelaysMillis")),
            MillisOf(TopologyPolicy().BrokerRungs()));
    }

    /// <summary>
    /// The declarations this library makes, from both halves of the topology.
    /// </summary>
    /// <remarks>
    /// Neither half is the whole thing, which is why the fixture records a
    /// <c>declaredBy</c> against every entry. The application declares its exchange,
    /// its queue and its binding; the consumer declares the rungs it will publish
    /// retries into. A test that looked at only one of them would find half a
    /// topology and call it correct.
    /// </remarks>
    private static async Task<Recorder> DeclaredByBothHalvesAsync()
    {
        var recorder = new Recorder();

        // The application's half, the same shape the fixture's generator builds:
        // exchange, queue with dead-lettering, binding.
        var declared = Topology.Define()
            .Exchange("orders", "topic")
            .QueueWithDeadLetter(Queue)
            .Bind(Queue, "orders", "order.*")
            .Build();

        foreach (var exchange in declared.Exchanges)
        {
            recorder.Exchange(exchange.Name, exchange.Type, exchange.Durable, "topology");
        }
        foreach (var queue in declared.Queues)
        {
            recorder.Queue(queue.Name, queue.Type, queue.Durable, queue.Arguments, "topology");
        }
        foreach (var binding in declared.Bindings)
        {
            recorder.Binding(binding.Queue, binding.Exchange, binding.RoutingKey, "topology");
        }

        // The consumer's half, which is literally what ConsumeAsync runs before it
        // subscribes.
        recorder.By = "consumer";
        await RetryLadder.For(Queue, TopologyPolicy()).DeclareAsync(recorder, CancellationToken.None);

        return recorder;
    }

    [Fact]
    public async Task TheDeclaredTopologyIsTheOneTheFixtureRecords()
    {
        var fixture = Section("topology");
        var recorder = await DeclaredByBothHalvesAsync();

        // Exchanges: name, type, durability.
        var exchanges = new List<string>();
        foreach (var e in fixture.GetProperty("exchanges").EnumerateArray())
        {
            var name = e.GetProperty("name").GetString()!;
            exchanges.Add(name);
            Assert.True(recorder.Exchanges.ContainsKey(name), $"nothing declared the exchange {name}");
            var actual = recorder.Exchanges[name];
            Assert.Equal(e.GetProperty("type").GetString(), actual.Type);
            Assert.Equal(e.GetProperty("durable").GetBoolean(), actual.Durable);
        }
        Assert.Equal(exchanges.OrderBy(n => n, StringComparer.Ordinal),
            recorder.Exchanges.Keys.OrderBy(n => n, StringComparer.Ordinal));

        // Queues: name, type, durability and the exact argument table.
        var queues = new List<string>();
        foreach (var q in fixture.GetProperty("queues").EnumerateArray())
        {
            var name = q.GetProperty("name").GetString()!;
            queues.Add(name);
            Assert.True(recorder.Queues.ContainsKey(name), $"nothing declared the queue {name}");
            var actual = recorder.Queues[name];

            Assert.Equal(
                q.GetProperty("type").GetString(),
                actual.Type.ToString().ToLowerInvariant());
            Assert.Equal(q.GetProperty("durable").GetBoolean(), actual.Durable);

            var expectedArgs = q.GetProperty("arguments").EnumerateObject()
                .ToDictionary(p => p.Name, p => Scalar(p.Value), StringComparer.Ordinal);
            var actualArgs = actual.Arguments.ToDictionary(
                p => p.Key,
                p => Convert.ToString(p.Value, CultureInfo.InvariantCulture)!,
                StringComparer.Ordinal);

            Assert.Equal(
                expectedArgs.OrderBy(p => p.Key, StringComparer.Ordinal),
                actualArgs.OrderBy(p => p.Key, StringComparer.Ordinal));
        }
        Assert.Equal(queues.OrderBy(n => n, StringComparer.Ordinal),
            recorder.Queues.Keys.OrderBy(n => n, StringComparer.Ordinal));

        // Bindings: queue, exchange and routing key, as a set.
        var bindings = fixture.GetProperty("bindings").EnumerateArray()
            .Select(b => Key(
                b.GetProperty("queue").GetString()!,
                b.GetProperty("exchange").GetString()!,
                b.GetProperty("routingKey").GetString()!))
            .OrderBy(k => k, StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(bindings, recorder.Bindings.Keys.OrderBy(k => k, StringComparer.Ordinal));
    }

    [Fact]
    public async Task EachHalfOfTheTopologyDeclaresWhatTheFixtureSaysItDoes()
    {
        var fixture = Section("topology");
        var recorder = await DeclaredByBothHalvesAsync();

        var disagreements = new List<string>();

        foreach (var e in fixture.GetProperty("exchanges").EnumerateArray())
        {
            var name = e.GetProperty("name").GetString()!;
            Compare(disagreements, "exchange " + name,
                e.GetProperty("declaredBy").GetString()!, recorder.Exchanges[name].By);
        }
        foreach (var q in fixture.GetProperty("queues").EnumerateArray())
        {
            var name = q.GetProperty("name").GetString()!;
            Compare(disagreements, "queue " + name,
                q.GetProperty("declaredBy").GetString()!, recorder.Queues[name].By);
        }
        foreach (var b in fixture.GetProperty("bindings").EnumerateArray())
        {
            var key = Key(
                b.GetProperty("queue").GetString()!,
                b.GetProperty("exchange").GetString()!,
                b.GetProperty("routingKey").GetString()!);
            Compare(disagreements, "binding " + key,
                b.GetProperty("declaredBy").GetString()!, recorder.Bindings[key]);
        }

        // Five entries, one difference, and it is about when rather than what. Java's
        // RetryTopology.declare() declares acemq.dlx, the dead-letter queue and the
        // parking queue when the consumer starts, so the fixture records them as
        // declared by both halves. This library declares exactly the same three
        // things, with the same types, durability and bindings — but on the settle
        // path, the first time a message is actually dead-lettered or parked, which is
        // asserted in
        // TheConsumerDeclaresTheDeadLetterQueuesWhenItFirstNeedsThemRatherThanAtStartUp.
        //
        // The end state on a broker is identical. The window in between is not: a
        // Java consumer leaves the two queues visible in the management UI from the
        // moment it connects, and a .NET one leaves them absent until something first
        // fails. Worth knowing before somebody writes an alert on their existence.
        Assert.Equal(
            new[]
            {
                "exchange acemq.dlx: fixture says both, here topology",
                "queue orders.new.dlq: fixture says both, here topology",
                "queue orders.new.parked: fixture says both, here topology",
                "binding orders.new.dlq|acemq.dlx|orders.new.dlq: fixture says both, here topology",
                "binding orders.new.parked|acemq.dlx|orders.new.parked: fixture says both, here topology",
            },
            disagreements);
    }

    private static void Compare(List<string> into, string what, string fixtureSays, string here)
    {
        if (fixtureSays != here) into.Add($"{what}: fixture says {fixtureSays}, here {here}");
    }

    [Fact]
    public async Task TheConsumerDeclaresTheDeadLetterQueuesWhenItFirstNeedsThemRatherThanAtStartUp()
    {
        var url = "memory://" + Guid.NewGuid().ToString("N");
        using var mq = await AceMqConnection.ConnectAsync(url);
        var queue = "orders" + Guid.NewGuid().ToString("N").Substring(0, 8);
        await mq.DeclareQueueAsync(queue);

        using var consumer = await mq.ConsumeAsync<string>(
            queue,
            ConsumerOptions.Defaults().WithRetry(RetryPolicy.Fixed(2, TimeSpan.FromSeconds(30))),
            _ => Task.FromResult(Ack.Park("nothing can be done with this")));

        // The rung is there from the moment the consumer started, because a rung that
        // does not exist drops the retry silently.
        Assert.True(await mq.QueueExistsAsync(Naming.RetryQueue(queue, TimeSpan.FromSeconds(30))));

        // The parking queue is not, which is where this library and Java differ.
        Assert.False(await mq.QueueExistsAsync(Naming.ParkedQueue(queue)));

        await mq.Publisher<string>("", queue).SendAsync("park me");

        var deadline = DateTime.UtcNow.AddSeconds(10);
        while (DateTime.UtcNow < deadline && !await mq.QueueExistsAsync(Naming.ParkedQueue(queue)))
        {
            await Task.Delay(10);
        }

        // And it is there once it is needed, with the message in it, so nothing is
        // lost by the wait — only the ability to see the queue before anything failed.
        Assert.True(await mq.QueueExistsAsync(Naming.ParkedQueue(queue)));
        Assert.Equal(1, await mq.MessageCountAsync(Naming.ParkedQueue(queue)));
    }

    // ---- queueTypeDefaults -----------------------------------------------

    [Fact]
    public void TheSourceQueueIsQuorumAndTheQueuesAroundItAreClassic()
    {
        var fixture = Section("queueTypeDefaults");

        Assert.Equal(fixture.GetProperty("sourceQueue").GetString(), TypeOf(Topology.Define().Queue("q"), "q"));
        Assert.Equal(
            fixture.GetProperty("sourceQueueWithDeadLetter").GetString(),
            TypeOf(Topology.Define().QueueWithDeadLetter("q"), "q"));
        Assert.Equal(
            fixture.GetProperty("explicitClassicQueue").GetString(),
            TypeOf(Topology.Define().Queue("q", QueueType.Classic), "q"));
        Assert.Equal(
            fixture.GetProperty("explicitClassicQueueWithDeadLetter").GetString(),
            TypeOf(Topology.Define().QueueWithDeadLetter("q", QueueType.Classic, null), "q"));
        Assert.Equal(
            fixture.GetProperty("deadLetterQueue").GetString(),
            TypeOf(Topology.Define().QueueWithDeadLetter("q"), "q.dlq"));
        Assert.Equal(
            fixture.GetProperty("parkedQueue").GetString(),
            TypeOf(Topology.Define().QueueWithDeadLetter("q"), "q.parked"));

        // The rung, taken from the consumer's own declaration rather than from a
        // topology, because that is the one two services race to declare.
        var rung = Topology.Define()
            .QueueWithRetry(Queue, RetryPolicy.Fixed(2, TimeSpan.FromMinutes(1)))
            .Build();
        Assert.Equal(
            fixture.GetProperty("retryRung").GetString(),
            TypeOf(rung, Queue + ".retry.1m"));

        // Quorum where it matters and classic where it does not, spelled out: a queue
        // declared quorum by one service and classic by another is not two queues, it
        // is a PRECONDITION_FAILED that stops the second one consuming at all.
        Assert.Equal("quorum", fixture.GetProperty("sourceQueue").GetString());
        Assert.Equal("classic", fixture.GetProperty("deadLetterQueue").GetString());
        Assert.Equal("classic", fixture.GetProperty("parkedQueue").GetString());
        Assert.Equal("classic", fixture.GetProperty("retryRung").GetString());
    }

    [Fact]
    public async Task EveryQueueThisLibraryDeclaresIsDurable()
    {
        var fixture = Section("queueTypeDefaults").GetProperty("durability");
        Assert.True(fixture.GetProperty("everyDeclaredQueueIsDurable").GetBoolean());

        var every = Topology.Define()
            .Queue("a")
            .Queue("b", QueueType.Classic)
            .QueueWithDeadLetter("c")
            .QueueWithDeadLetter("d", QueueType.Classic, null)
            .QueueWithRetry("e", RetryPolicy.Fixed(2, TimeSpan.FromMinutes(1)))
            .Build();

        Assert.NotEmpty(every.Queues);
        foreach (var queue in every.Queues) Assert.True(queue.Durable, queue.Name + " is not durable");

        // And the consumer's half too, which the builder above does not cover.
        var recorder = await DeclaredByBothHalvesAsync();
        foreach (var queue in recorder.Queues) Assert.True(queue.Value.Durable, queue.Key + " is not durable");
        foreach (var exchange in recorder.Exchanges)
        {
            Assert.True(exchange.Value.Durable, exchange.Key + " is not durable");
        }
    }

    private static string TypeOf(Topology.Builder builder, string queue) => TypeOf(builder.Build(), queue);

    private static string TypeOf(Topology topology, string queue)
    {
        foreach (var spec in topology.Queues)
        {
            if (spec.Name == queue) return spec.Type.ToString().ToLowerInvariant();
        }
        throw new InvalidOperationException($"no queue named {queue} in that topology");
    }

    // ---- plumbing --------------------------------------------------------

    private static string Key(string queue, string exchange, string routingKey) =>
        $"{queue}|{exchange}|{routingKey}";

    private static string Scalar(JsonElement value) => value.ValueKind switch
    {
        JsonValueKind.Number => value.GetInt64().ToString(CultureInfo.InvariantCulture),
        JsonValueKind.True => "True",
        JsonValueKind.False => "False",
        _ => value.GetString()!,
    };

    /// <summary>
    /// A connection that records declarations instead of making them, so that what
    /// the consumer's half of the topology declares can be compared without a broker.
    /// </summary>
    /// <remarks>
    /// The counterpart to the <c>Recorder</c> inside Java's fixture generator. Every
    /// method that is not a declaration throws: this exists to be declared at, and a
    /// test that reached one of them would be testing something else.
    /// </remarks>
    private sealed class Recorder : ITransportConnection
    {
        public string By { get; set; } = "topology";

        public Dictionary<string, (string Type, bool Durable, string By)> Exchanges { get; } =
            new Dictionary<string, (string, bool, string)>(StringComparer.Ordinal);

        public Dictionary<string, (QueueType Type, bool Durable,
            IReadOnlyDictionary<string, object> Arguments, string By)> Queues { get; } =
            new Dictionary<string, (QueueType, bool, IReadOnlyDictionary<string, object>, string)>(
                StringComparer.Ordinal);

        public Dictionary<string, string> Bindings { get; } =
            new Dictionary<string, string>(StringComparer.Ordinal);

        public void Exchange(string name, string type, bool durable, string by)
        {
            // "both" rather than a last-writer-wins: a name declared by the
            // application and by the consumer is exactly what the fixture's
            // declaredBy is for.
            if (Exchanges.TryGetValue(name, out var seen) && seen.By != by)
            {
                Exchanges[name] = (seen.Type, seen.Durable, "both");
                return;
            }
            Exchanges[name] = (type, durable, by);
        }

        public void Queue(
            string name, QueueType type, bool durable,
            IReadOnlyDictionary<string, object> arguments, string by)
        {
            if (Queues.TryGetValue(name, out var seen) && seen.By != by)
            {
                Queues[name] = (seen.Type, seen.Durable, seen.Arguments, "both");
                return;
            }
            Queues[name] = (type, durable, arguments, by);
        }

        public void Binding(string queue, string exchange, string routingKey, string by)
        {
            var key = Key(queue, exchange, routingKey);
            if (Bindings.TryGetValue(key, out var seen) && seen != by)
            {
                Bindings[key] = "both";
                return;
            }
            Bindings[key] = by;
        }

        public Task DeclareExchangeAsync(
            string name, string type, bool durable, CancellationToken cancellationToken)
        {
            Exchange(name, type, durable, By);
            return Task.CompletedTask;
        }

        public Task DeclareQueueAsync(
            string name, QueueType type, bool durable,
            IReadOnlyDictionary<string, object>? arguments, CancellationToken cancellationToken)
        {
            Queue(name, type, durable, arguments ?? new Dictionary<string, object>(), By);
            return Task.CompletedTask;
        }

        public Task BindQueueAsync(
            string queue, string exchange, string routingKey, CancellationToken cancellationToken)
        {
            Binding(queue, exchange, routingKey, By);
            return Task.CompletedTask;
        }

        private static Exception OnlyDeclarations() =>
            new NotSupportedException("the recorder only records declarations");

        public Task<ConfirmResult> SendAsync(OutboundMessage message, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task<ISubscription> SubscribeAsync(
            string queue, int prefetch, IReadOnlyDictionary<string, object>? arguments,
            Func<InboundDelivery, Task<Ack>> handler, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task<InboundDelivery?> ReceiveAsync(
            string queue, TimeSpan timeout, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task<IPulledDelivery?> PullAsync(
            string queue, TimeSpan timeout, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task<long> MessageCountAsync(string queue, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task DeleteQueueAsync(string name, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task DeleteExchangeAsync(string name, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public Task<bool> QueueExistsAsync(string name, CancellationToken cancellationToken) =>
            Task.FromResult(Queues.ContainsKey(name));

        public Task<QueueCheck> CheckQueueAsync(
            string name, QueueType type, bool durable,
            IReadOnlyDictionary<string, object>? arguments, CancellationToken cancellationToken) =>
            throw OnlyDeclarations();

        public bool IsOpen => true;

        public bool IsBlocked => false;

        public string? BlockedReason => null;

        public void Dispose()
        {
        }
    }
}
