// Copyright 2026 AceMQ.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Data.Common;
using System.Text.Json;
using AceMq.Amqp;
using Microsoft.Data.Sqlite;
using AvroSchema = global::Avro.Schema;
using GenericRecord = global::Avro.Generic.GenericRecord;

namespace AceMq.Amqp.Avro.Tests;

/// <summary>
/// Asserts this library against <c>fixtures/avro-resolution-fixtures.json</c>, the
/// shared record of when an AceMQ library resolves an Avro message onto a reader
/// schema and what the message decodes to when it does not.
/// </summary>
/// <remarks>
/// <para>
/// The fixture is generated by <c>acemq-java-amqp</c> and every library commits a
/// byte-for-byte copy; <c>../scripts/check-fixtures.sh</c> fails if any copy has
/// drifted. The bodies here were written by Java, so what these tests compare is not
/// two libraries agreeing with the same prose but this one agreeing with the other's
/// bytes.
/// </para>
/// <para>
/// The rule the fixture pins is one sentence and it is the same in all five
/// languages: <strong>resolution happens when the library has a reader schema to
/// resolve onto.</strong> Where a reader schema comes from is what differs. In this
/// library the codec is constructed with a schema, so
/// <c>AvroCodec.Registered(registry, schema)</c> always has one and .NET lands on the
/// fixture's <c>resolved</c> column — which is what the first half of each test below
/// asserts.
/// </para>
/// <para>
/// The second half asserts the <c>writerShape</c> column, which this library can now
/// also be asked for: <see cref="AvroCodec.WithoutReaderSchema"/> declines resolution
/// and reads every message with the shape its writer gave it. Pinning both columns
/// rather than only this library's default is the point — the opt-out is a claim
/// about somebody else's bytes, and these are somebody else's bytes.
/// </para>
/// <para>
/// <strong>One thing the fixture says that is no longer quite true here.</strong> It
/// puts this library in the <c>resolved</c> column because "the codec is constructed
/// with a schema, so there is always one to resolve onto", and says of Java that it
/// "is the only one of the five that shows both columns". Both sentences were written
/// before <c>WithoutReaderSchema()</c> existed. The column is still right as this
/// library's default, which is what <see cref="LandsOnTheColumnTheFixtureAssignsThisLibrary"/>
/// asserts — but "always" is now "unless asked otherwise", and the four tests above
/// are .NET showing both columns. That is a note for whoever regenerates the fixture,
/// not a behaviour difference: the decoded values under each column are exactly what
/// the fixture records.
/// </para>
/// </remarks>
public sealed class AvroResolutionConformanceTests : IDisposable
{
    private readonly string _db =
        "Data Source=file:" + Guid.NewGuid().ToString("N") + "?mode=memory&cache=shared";

    private SqliteConnection? _keepAlive;

    public void Dispose() => _keepAlive?.Dispose();

    private DbConnection Connect()
    {
        var c = new SqliteConnection(_db);
        c.Open();
        return c;
    }

    /// <summary>
    /// A registry answering the fixture's ids with the fixture's writer schemas.
    /// </summary>
    /// <remarks>
    /// The same SQLite-backed <c>DbSchemaRegistry</c> the rest of this suite uses,
    /// rather than a second fake invented for these two tests. The one difference is
    /// that the rows are inserted with the ids the fixture names instead of the ones
    /// <c>IdFor</c> would hand out: these bodies were framed by another library, and
    /// the id in the frame is the fixture's, not this process's counter.
    /// </remarks>
    private DbSchemaRegistry RegistryAnswering(params (int Id, string Definition)[] schemas)
    {
        var registry = new DbSchemaRegistry(Connect);
        _keepAlive = new SqliteConnection(_db);
        _keepAlive.Open();

        foreach (var statement in registry.CreateTableSql().Split(';'))
        {
            if (statement.Trim().Length == 0) continue;
            using var create = _keepAlive.CreateCommand();
            create.CommandText = statement;
            create.ExecuteNonQuery();
        }

        foreach (var (id, definition) in schemas)
        {
            // Registered under the exact text the fixture carries, not a re-rendering
            // of a parsed schema: the identifier stands for those bytes, and Avro does
            // not promise to render a parsed schema back the way it came in.
            var schema = new SchemaDefinition("avro", SubjectOf(definition), definition);
            using var insert = _keepAlive.CreateCommand();
            insert.CommandText =
                "INSERT INTO acemq_schema (id, fingerprint, format, subject, definition) " +
                "VALUES ($id, $fingerprint, $format, $subject, $definition)";
            insert.Parameters.AddWithValue("$id", id);
            insert.Parameters.AddWithValue("$fingerprint", schema.Fingerprint);
            insert.Parameters.AddWithValue("$format", schema.Format);
            insert.Parameters.AddWithValue("$subject", schema.Subject);
            insert.Parameters.AddWithValue("$definition", schema.Definition);
            insert.ExecuteNonQuery();
        }

        return registry;
    }

    private static string SubjectOf(string schemaJson) =>
        ((global::Avro.NamedSchema)AvroSchema.Parse(schemaJson)).Fullname;

    // ---- the fixture -----------------------------------------------------

    private static JsonElement Case(string name)
    {
        // Copied beside the other shared fixtures, in AceMq.Amqp.Tests/fixtures, and
        // linked into this project's output so there is one file on disk for
        // check-fixtures.sh to compare rather than two that can disagree.
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "avro-resolution-fixtures.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        foreach (var c in doc.RootElement.GetProperty("cases").EnumerateArray())
        {
            if (c.GetProperty("case").GetString() == name) return c.Clone();
        }
        throw new InvalidOperationException($"no fixture case '{name}' in {path}");
    }

    /// <summary>The column the fixture says a decode should have produced.</summary>
    private static void AssertDecodedAs(JsonElement column, GenericRecord record)
    {
        // The field names first, in the order the schema declares them. Doing this
        // before the values is what catches the failure that matters: a spare field
        // the reader never declared, or a declared one the decode left out.
        var expectedNames = column.EnumerateObject().Select(f => f.Name).ToList();
        var actualNames = record.Schema.Fields.Select(f => f.Name).ToList();
        Assert.Equal(expectedNames, actualNames);

        foreach (var field in column.EnumerateObject())
        {
            Assert.True(
                record.TryGetValue(field.Name, out var actual),
                $"the decoded record has no field '{field.Name}'");

            if (field.Value.ValueKind == JsonValueKind.Number)
            {
                Assert.Equal(field.Value.GetInt32(), Assert.IsType<int>(actual));
            }
            else
            {
                Assert.Equal(field.Value.GetString(), Assert.IsType<string>(actual));
            }
        }
    }

    private static GenericRecord Decode(AvroCodec codec, JsonElement fixture) =>
        (GenericRecord)codec.Decode(
            Convert.FromBase64String(fixture.GetProperty("bodyBase64").GetString()!),
            typeof(GenericRecord));

    private (AvroCodec Resolving, AvroCodec AsWritten, JsonElement Fixture) Codecs(string caseName)
    {
        var fixture = Case(caseName);
        var registry = RegistryAnswering(
            (fixture.GetProperty("schemaId").GetInt32(),
             fixture.GetProperty("writerSchema").GetString()!));
        var readerSchema = fixture.GetProperty("readerSchema").GetString()!;

        var resolving = AvroCodec.Registered(registry, readerSchema);
        return (resolving, resolving.WithoutReaderSchema(), fixture);
    }

    // ---- field removed by the writer -------------------------------------

    /// <summary>
    /// The case that matters. The writer never sent <c>currency</c>; the reader
    /// declares it with a default of <c>"GBP"</c>, which is deliberately not the
    /// type's zero value, so a decode that skipped resolution cannot pass by
    /// accident.
    /// </summary>
    [Fact]
    public void FillsInAFieldTheWriterRemoved()
    {
        var (resolving, _, fixture) = Codecs("field-removed-by-the-writer");

        Assert.NotNull(resolving.ReaderSchema);
        AssertDecodedAs(fixture.GetProperty("resolved"), Decode(resolving, fixture));
    }

    [Fact]
    public void LeavesAFieldTheWriterRemovedAbsentWhenResolutionIsDeclined()
    {
        var (_, asWritten, fixture) = Codecs("field-removed-by-the-writer");

        Assert.Null(asWritten.ReaderSchema);
        AssertDecodedAs(fixture.GetProperty("writerShape"), Decode(asWritten, fixture));
    }

    // ---- field added by the writer ---------------------------------------

    /// <summary>
    /// The direction everybody assumes is the dangerous one and is not: the unknown
    /// field is skipped, and the fields after it in the writer's record still come
    /// back correct.
    /// </summary>
    [Fact]
    public void SkipsAFieldTheWriterAddedThatTheReaderDoesNotDeclare()
    {
        var (resolving, _, fixture) = Codecs("field-added-by-the-writer");

        AssertDecodedAs(fixture.GetProperty("resolved"), Decode(resolving, fixture));
    }

    [Fact]
    public void KeepsAFieldTheWriterAddedWhenResolutionIsDeclined()
    {
        var (_, asWritten, fixture) = Codecs("field-added-by-the-writer");

        AssertDecodedAs(fixture.GetProperty("writerShape"), Decode(asWritten, fixture));
    }

    // ---- the fixture's own claims ----------------------------------------

    /// <summary>
    /// The row the fixture assigns this library, asserted rather than assumed.
    /// </summary>
    /// <remarks>
    /// The two columns above would still both pass if somebody flipped this
    /// library's default, because both are reached explicitly. This is the assertion
    /// that would not: .NET is listed as <c>resolved</c>, and what makes that true is
    /// that a codec built the ordinary way already holds a reader schema.
    /// </remarks>
    [Fact]
    public void LandsOnTheColumnTheFixtureAssignsThisLibrary()
    {
        var fixture = Case("field-removed-by-the-writer");
        var registry = RegistryAnswering(
            (fixture.GetProperty("schemaId").GetInt32(),
             fixture.GetProperty("writerSchema").GetString()!));

        var codec = AvroCodec.Registered(registry, fixture.GetProperty("readerSchema").GetString()!);

        Assert.Equal("resolved", ColumnFor("acemq-dotnet-amqp"));
        Assert.NotNull(codec.ReaderSchema);
        Assert.Equal(codec.Schema.ToString(), codec.ReaderSchema!.ToString());
    }

    private static string ColumnFor(string library)
    {
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "avro-resolution-fixtures.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        foreach (var entry in doc.RootElement.GetProperty("libraries").EnumerateArray())
        {
            if (entry.GetProperty("library").GetString() == library)
            {
                return entry.GetProperty("column").GetString()!;
            }
        }
        throw new InvalidOperationException($"the fixture does not list {library}");
    }

    /// <summary>
    /// The three-argument form reaches the same column, by a different route.
    /// </summary>
    /// <remarks>
    /// A service that publishes one version and consumes another: only the written
    /// schema is registered, and the reader schema named separately is what every
    /// message resolves onto. The fixture's two schemas make this the same decode as
    /// the default case, which is the point — the reader schema is the reader schema
    /// however it got there.
    /// </remarks>
    [Fact]
    public void ResolvesOntoAReaderSchemaNamedSeparately()
    {
        var fixture = Case("field-removed-by-the-writer");
        var registry = RegistryAnswering(
            (fixture.GetProperty("schemaId").GetInt32(),
             fixture.GetProperty("writerSchema").GetString()!));

        var codec = AvroCodec.Registered(
            registry,
            fixture.GetProperty("writerSchema").GetString()!,
            fixture.GetProperty("readerSchema").GetString()!);

        AssertDecodedAs(fixture.GetProperty("resolved"), Decode(codec, fixture));
    }
}
